
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8881



dubbo:
  application:
    name: service-provider

  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper

  protocol:
    name: dubbo
    port: 20880

  monitor:
    protocol: registry